on:
  push:
    tags:
    - '*'
jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [
          aarch64-linux-gnu,
          aarch64-linux-musl,
          x86_64-linux-gnu,
          x86_64-linux-musl,
          aarch64-macos,
          x86_64-macos,
          x86_64-windows-gnu,
          x86-linux-gnu,
          x86-linux-musl,
          x86-windows,
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build -Dtarget=${{ matrix.target }}
      - name: zip artifact
        run: |
          cd zig-out/ && tar -czvf ../lua_${{ matrix.target }}.tar.gz .
      - uses: actions/upload-artifact@v4
        with:
          name: lua_${{ matrix.target }}
          path: |
            ./lua_${{ matrix.target }}.tar.gz
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build-release 
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.tar.gz"
